# [Choice] Debian version (use bullseye on local arm64/Apple Silicon): bookworm, bullseye, buster
FROM buildpack-deps:${templateOption:imageVariant}-curl

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>